import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1680, height: 900 }, deviceScaleFactor: 2 });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
await page.click('.twin-tabs button:nth-child(2)');
await page.waitForTimeout(1000);
await page.screenshot({ path: 'shots/qa/work-zoom.png', clip: { x: 430, y: 380, width: 520, height: 360 } });
console.log('done');
await browser.close();
